Style/Encoding:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 25

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false

Style/LeadingCommentSpace:
  Enabled: false

Style/SingleSpaceBeforeFirstArg:
  Enabled: false

IndentationConsistency:
  Enabled: false
ClassAndModuleChildren:
  Enabled: false

AllCops:
  Exclude:
    - 'lib/**/*'
    - 'bin/**/*'
    - 'spec/**/*'
    - 'node_modules/**/*'
    - 'Guardfile'
    - 'db/schema.rb'
