SectorsConstants = Marty.createConstants [
  "SECTOR_CREATE"
  "SECTOR_CREATE_RESPONSE"
  "SECTOR_EDIT"
  "SECTOR_CANCEL"
  "SECTOR_UPDATE"
  "SECTOR_UPDATE_TEXT"
  "SECTOR_UPDATE_RESPONSE"
  "SECTOR_SAVE"
  "SECTOR_DELETE"
  "SECTOR_DELETE_RESPONSE"
  "SECTOR_MOVE"
  "SECTOR_MOVE_RESPONSE"
]

module.exports = SectorsConstants