SubsectorsConstants = Marty.createConstants [
  "SUBSECTOR_CREATE"
  "SUBSECTOR_CREATE_RESPONSE"
  "SUBSECTOR_EDIT"
  "SUBSECTOR_CANCEL"
  "SUBSECTOR_UPDATE"
  "SUBSECTOR_UPDATE_TEXT"
  "SUBSECTOR_UPDATE_RESPONSE"
  "SUBSECTOR_SAVE"
  "SUBSECTOR_DELETE"
  "SUBSECTOR_DELETE_RESPONSE"
  "SUBSECTOR_MOVE"
  "SUBSECTOR_MOVE_RESPONSE"
]

module.exports = SubsectorsConstants